services:
  laravel.test:
    build:
      context: "./vendor/laravel/sail/runtimes/8.4"
      dockerfile: Dockerfile
      args:
        WWWGROUP: "${WWWGROUP}"
    image: "sail-8.4/app"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${APP_PORT:-80}:80"
      - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
    environment:
      WWWUSER: "${WWWUSER}"
      LARAVEL_SAIL: 1
      XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
      XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
      IGNITION_LOCAL_SITES_PATH: "${PWD}"
    volumes:
      - ".:/var/www/html"
    networks:
      - sail
    depends_on:
      - redis-sentinel-1
      - redis-sentinel-2
      - redis-sentinel-3

  # Redis + Sentinel Node 1 (Master)
  redis-sentinel-1:
    image: redis:7-alpine
    container_name: redis-sentinel-1
    volumes:
      - ./docker/redis/redis-master.conf:/usr/local/etc/redis/redis.conf
      - ./docker/redis/sentinel.conf:/usr/local/etc/redis/sentinel.conf
      - ./docker/startup.sh:/startup.sh
    command: /startup.sh master
    ports:
      - "6379:6379"
      - "26379:26379"
    networks:
      - sail
    restart: unless-stopped

  # Redis + Sentinel Node 2 (Slave)
  redis-sentinel-2:
    image: redis:7-alpine
    container_name: redis-sentinel-2
    volumes:
      - ./docker/redis/redis-slave.conf:/usr/local/etc/redis/redis.conf
      - ./docker/redis/sentinel.conf:/usr/local/etc/redis/sentinel.conf
      - ./docker/startup.sh:/startup.sh
    command: /startup.sh slave
    networks:
      - sail
    depends_on:
      - redis-sentinel-1
    restart: unless-stopped

  # Redis + Sentinel Node 3 (Slave)
  redis-sentinel-3:
    image: redis:7-alpine
    container_name: redis-sentinel-3
    volumes:
      - ./docker/redis/redis-slave.conf:/usr/local/etc/redis/redis.conf
      - ./docker/redis/sentinel.conf:/usr/local/etc/redis/sentinel.conf
      - ./docker/startup.sh:/startup.sh
    command: /startup.sh slave
    networks:
      - sail
    depends_on:
      - redis-sentinel-1
    restart: unless-stopped

networks:
  sail:
    driver: bridge
